import numpy as np
import matplotlib.pyplot as plt

A = np.array([[0,1], [1, 0]])
print("the matrix A=", A)
ev1, ev2 = np.linalg.eig(A)
print("The Eigen values of A are", ev1.real)
print("The Eigen vactors of A are", ev2.real)
plt.figure()
plt.axhline()
plt.axvline()
plt.xlim(-3, 3)
plt.ylim(-3, 3)
plt.gca().set_aspect("equal")
plt.quiver(0, 0, ev2[0, 0], ev2[1, 0], angles="xy", scale_units="xy", scale=1)
plt.quiver(0, 0, ev2[0, 1], ev2[1, 1], angles="xy", scale_units="xy", scale=1)
plt.title("Eigen vectors of the matrix A")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.show()
